# Generated by Django 2.2 on 2021-10-01 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enroll_date', models.DateTimeField(null=True, verbose_name='Enroll Date')),
                ('close_date', models.DateTimeField(null=True, verbose_name='Close Date')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Score')),
                ('status', models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('REPROVED', 'REPROVED'), ('IN_PROGRESS', 'IN_PROGRESS')], max_length=100, null=True, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Student')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='Student')),
            ],
            options={
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollment',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
